name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: CI Pipeline
        uses: ./.github/workflows/ci-pipeline.yml

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - name: CD Pipeline
        uses: ./.github/workflows/cd-pipeline.yml
